### ISSUE TITLE
Download OK but GUI throwing an error

### ISSUE THREAD

**Issue by KawaKode** [cstaelen/tidarr#1]
Hello, 

First of all, your apps works great, Tidal-DL does it's job wonderfully.
The only issue I have is "cosmetic".

![image](https://github.com/cstaelen/tidarr/assets/75862028/0e28c815-562c-48b1-ad35-3e6431d5edc7)

You see, I have mapped my music folder directly to the download folder inside the container but I noticed that after the Download completes, there's some kind of script that wants to move the downloaded files elsewhere, but it's not very useful as I just want to download straight to my music folder.
Here is an example of the issue :
![image](https://github.com/cstaelen/tidarr/assets/75862028/75a6aa20-2b77-4906-a7b3-c11d7e97dd1e)

It would be nice to add the option to not move the files at the end of a download.

**Comment by cstaelen** [comment]
@KawaKode thanks for your feedback ! 

Could you please try to mount a new volume by adding in your `docker-compose.yml` : 
`-v /mnt/d4/incomplete:/home/app/standalone/download/incomplete \`

**Comment by cstaelen** [comment]
Btw @KawaKode , what is the download path specified in `/docker/tidarr/config/.tidal-dl.json` ?
You should have this existing line : ` "downloadPath": "./download/incomplete",` 

You also can try to use the absolute path ` "downloadPath": "/home/app/standalone/download/incomplete",`

**Comment by kawakode** [comment]
I changed the path in the config before that, but by mapping the incomplete folder to my Musique folder, it seems to not error out anymore. So what I'll do is map the incomplete folder in a temp folder on my docker instance and keep my Musique folder mapped to the configured path in the .tidal-dl.json.

Thanks for your time !

**Comment by cstaelen** [comment]
Good news 👍 
Thank you for your interest =)

**Comment by kawakode** [comment]
UPDATE : Don't map the incomplete to your actual music folder, it will
erase everything in it  Don't ask me why I know that 🙃

**Comment by cstaelen** [comment]
I could warn you about this indeed 😶 .
incomplete folder is just a "temp directory" using to receive downloads before >  processing > beeting (optional) > moving to `tracks` or `album` folder  > cleaning. 👍
