### ISSUE TITLE
Ability to use album URLs to download them

### ISSUE THREAD

**Issue by KawaKode** [cstaelen/tidarr#2]
Hello !

The search tool is working well, except when it doesn't find something.
For example, when searching for albums by _Fluke_, I cannot find "[_Risotto_](https://listen.tidal.com/album/161163) even when scrolling a lot.

And pasting the link to the album doesn't work either, even just the album ID isn't working :
![image](https://github.com/cstaelen/tidarr/assets/75862028/0caf2546-42a5-4968-b929-cf288c24acbf)

Adding the option to either filter by artist (but in a strict manner, not just pasting the artist's name in the search box) or by adding the ability to paste in links to albums/tracks/EPs, etc...

Best regards, 
Kawa.

**Comment by cstaelen** [comment]
Hi @KawaKode I'd love adding this feature too !! 
But I did not find many ressources explaining the tidal api.
If you (or anyone) found some please share :)

**Comment by cstaelen** [comment]
After few research, I think DL by url or id should be easy to implement.
But I'm still looking for a way to query by artist using a "strict-manner" 👍

**Comment by kawakode** [comment]
Thank you for your time, I wish I'd help more but I'm really not well
versed in dev :/

**Comment by cstaelen** [comment]
I found a way to achieve both search by url and strict artist querying 👌 
It will be shipped in next release. 

Thanks for you feedback !

**Comment by cstaelen** [comment]
@KawaKode I pushed a fresh new docker image (0.0.4) including the features mentionned above.
You can pull image with `cstaelen/tidarr:latest` tag 👍

**Comment by kawakode** [comment]
Hello,

I updated to 0.0.4, the option to only search albums by a certain artist works great, using links too but, a little caveat : some albums are just impossible to find, like in my first post, the album "Risotto" by Fluke is not showing and the direct link doesn't work either. Now this album is flagged as "Explicit" by Tidal so maybe something's up with that ? I'll test that a bit more today.

**Comment by cstaelen** [comment]
I will check this specific case.
Maybe country code could restricts some results. 
Could you please try to set the same country code as your tidal account if not already set?

**Comment by cstaelen** [comment]
Btw i broke the pager ... I will fix this asap

**Comment by cstaelen** [comment]
> Hello,
> 
> I updated to 0.0.4, the option to only search albums by a certain artist works great, using links too but, a little caveat : some albums are just impossible to find, like in my first post, the album "Risotto" by Fluke is not showing and the direct link doesn't work either. Now this album is flagged as "Explicit" by Tidal so maybe something's up with that ? I'll test that a bit more today.

Seems to be OK with country code FR 👍 

You can override it using docker environment var :
`- NEXT_PUBLIC_TIDAL_COUNTRY_CODE=FR`

<img width="623" alt="Capture d’écran 2023-12-24 à 23 10 44" src="https://github.com/cstaelen/tidarr/assets/5319804/3d5afd07-70d7-471f-b67a-cb3d5674ad8d">

**Comment by cstaelen** [comment]
> Btw i broke the pager ... I will fix this asap

Fixed in 0.0.4 with some other small issues. You can docker pull 👍

**Comment by kawakode** [comment]
> > Hello,
> > I updated to 0.0.4, the option to only search albums by a certain artist works great, using links too but, a little caveat : some albums are just impossible to find, like in my first post, the album "Risotto" by Fluke is not showing and the direct link doesn't work either. Now this album is flagged as "Explicit" by Tidal so maybe something's up with that ? I'll test that a bit more today.
> 
> Seems to be OK with country code FR 👍
> 
> You can override it using docker environment var : `- NEXT_PUBLIC_TIDAL_COUNTRY_CODE=FR`
> <img alt="Capture d’écran 2023-12-24 à 23 10 44" width="623" src="https://private-user-images.githubusercontent.com/5319804/292690851-3d5afd07-70d7-471f-b67a-cb3d5674ad8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NTg1NjksIm5iZiI6MTcwMzQ1ODI2OSwicGF0aCI6Ii81MzE5ODA0LzI5MjY5MDg1MS0zZDVhZmQwNy03MGQ3LTQ3MWYtYjY3YS1jYjNkNTY3NGFkOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMjI1MTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUwZTM4ODdmNzIyMGJmZDBlYzUyMDY5YmM0OWI3N2E0N2EyN2UxZjlkZDNlZmZiMWU4Y2ZlMjE4YWU4Y2U4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OQRW3y7FxuPxxCXL4wVunEqFAHmMIqPEYyzrMSrX-Q4">

I tried to use that env variable but it doesn't seem to apply, I have a substitution error : 
![Screenshot_20231225-000700](https://github.com/cstaelen/tidarr/assets/75862028/5e8a64e6-b349-4f8c-8267-ce69326a4fc1)

**Comment by cstaelen** [comment]
@KawaKode I fixed this.
 Substitution errors still remains but country code override should works anyway 🙏 
 I can pull 0.0.4 or latest image (hoping everything get fine this time ;) )

**Comment by kawakode** [comment]
It works perfectly now !
Thanks a lot and merry Christmas:)

**Comment by cstaelen** [comment]
Thanks to you helping me to enhance the app !! Merry christmas too :)
