### ISSUE TITLE
Display bug when popularity at 0

### ISSUE THREAD

**Issue by KawaKode** [cstaelen/tidarr#3]
Hello,

I noticed that when the popularity is at zero for a track/album, the CSS seems to not apply : 
![image](https://github.com/cstaelen/tidarr/assets/75862028/81b78d53-be58-40c5-b966-a0eb428dc4eb)

**Comment by cstaelen** [comment]
Hi @KawaKode this issue has been fix in 0.0.4 docker image 👍 
You can pull latest image tag to get the fix.

Btw, i just released a first version of Shazarr : a Shazam companion app for Tidarr and Lidarr 👌 
https://github.com/cstaelen/docker-shazarr
This is a very early alpha, but should work pretty well on Android device :)

**Comment by kawakode** [comment]
Thanks ! I'll test that out !
