### ISSUE TITLE
cant pull image

### ISSUE THREAD

**Issue by diegocade1** [cstaelen/tidarr#42]
Hello, as the tittle says, currently I cant pull the docker image, I get the following message:

```
~$ docker image pull cstaelen/tidarr
'Using default tag: latest
Error response from daemon: manifest for cstaelen/tidarr:latest not found: manifest unknown: manifest unknown
``` 
Any idea what could it be?

thanks.

**Comment by cstaelen** [comment]
Hello, I messed up the 0.1.8, I just revert the `latest` tag.
It should now target 0.1.7 version as before 👍
