### ISSUE TITLE
Feature request for single tracks + track radios

### ISSUE THREAD

**Issue by Fonta** [cstaelen/tidarr#48]
When searching for track URLs it shows 0 results.
Would be nice to be able to download a single track.

Also would be able to enter a track radio url.

**Comment by cstaelen** [comment]
Hello,

I can deliver pretty quickly "download track by url" feature.

About radio url, could you please provide me an example url ?

Thanks for your feeback :)

**Comment by fonta** [comment]
Sounds great :)

Here's an example URL for the track/artist radio
https://tidal.com/browse/mix/00166fec481604e645532e233b958b
https://tidal.com/browse/mix/000aa824749d0ebd070d39bd8e2d93

Ps. found out that if you copy an url from tidal, it sometimes adds ?u to the end which you need to remove or it won't find album/track.
Example: https://tidal.com/browse/track/77610759?u

**Comment by cstaelen** [comment]
Ok :) it seems clear to me !

I think i can handle mix and track url download 👌

Wait and see for the next release 🚀

**Comment by fonta** [comment]
Sounds awesome, thx!

**Comment by cstaelen** [comment]
- [x] Download tracks by track URL
- [x] Strip `?...` string in URL
- [ ] Download radios/mixes by URL

For now, `tiddl` project does not provide any solution to download entire radios / mixes.

<img width="936" alt="Capture d’écran 2024-12-24 à 13 32 09" src="https://github.com/user-attachments/assets/83f4d80f-79fc-4118-9063-25f8033e95bc" />

I will ask the author if he could add this feature :) 

Anyway, I can at least retrieve all tracks of the radio/mix and download them :

<img width="1197" alt="Capture d’écran 2024-12-24 à 13 35 08" src="https://github.com/user-attachments/assets/8f73ebe6-5a16-4f45-bf4a-034223a06910" />

Are you interested in by this workaround  ?

**Comment by fonta** [comment]
Awesome :)

No need to implement the workaround if tiddl doesn't support it OOB.
I just found another way by adding the radio to a new playlist and then download the playlist
Being able to directly download the mix would still be easier though.

<img width="612" alt="Screenshot 2024-12-24 at 13 51 00@2x" src="https://github.com/user-attachments/assets/44b49a6d-56a0-46e6-be38-4a83eaaac5c4" />

**Comment by cstaelen** [comment]
Great ! 
I think I will deliver the feature anyway and add a text message to suggest your trick to be able to download the entire mix 👍

**Comment by fonta** [comment]
Awesome, thx!

**Comment by cstaelen** [comment]
Hello @Fonta 
I just released 0.1.10 :

### 🚀 Added
* [Front] Search track by direct URL
* [Front] Search mix/radio by direct URL
### 🐛 Fixed
* [Front] Fix URL search - strip URL query params

Thank you so much for your help 🙏 
Merry Christmas 🎄 😉

**Comment by fonta** [comment]
Tested and works.
Thanks!

Merry Christmas! 🎄
