### ISSUE TITLE
Bad implementation of copy from incomplete to complete

### ISSUE THREAD

**Issue by rclarsfull** [cstaelen/tidarr#6]
File: https://github.com/cstaelen/tidarr/blob/main/api/src/services/tidal-dl.ts
This Line in you code fuckt up my incomplete dictonary of my other *arr apps:
```const output_move = execSync(`cp -rf ${ROOT_PATH}/download/incomplete/* ${ROOT_PATH}/download/tracks/`, { encoding: "utf-8" });```
pls only try to move the downloaded stuff. not everything in that folder.
This mad it seem like the program frozze on copy. buit it just tryed to copy 500 gb

**Comment by cstaelen** [comment]
At this step, typescript does not know the folder/album name downloaded from python tidal-dl .
So i can't target the  newly downloaded album folder to move it in the right place.

Maybe we could parse tidal-dl output to retrieve the folder name.
For now, please, use a specific incomplete folder for Tidarr.

I will update readme.

**Comment by cstaelen** [comment]
After looking further, tidarr incomplete folder should not be mounted neither shared indeed.
Content is purged after each download.
