### ISSUE TITLE
[help] download entire playlist

### ISSUE THREAD

**Issue by michaellunzer** [cstaelen/tidarr#7]
hey @cstaelen great job with this app! I got it working relatively easily on my unRaid server 😄 

I'm not sure if I'm interpreting it right, but is there a way to grab an entire (public) playlist? 

I'm trying to think of ways to automate everything so it'd be awesome if it could watch a playlist and when new tracks are added, it goes out and grabs them for me. Is that something that you could add to the roadmap? 

Thanks!

**Comment by cstaelen** [comment]
Hi @michaellunzer thanks for your feedback ! 
Glad to hear it works on unRaid 👍 

For now, they are no UI to handle playlists and no DB system to work on automation.
But maybe you can use [`tidal-dl`](https://github.com/yaronzz/Tidal-Media-Downloader) binary in some way like : 
```
docker compose exec -it tidarr tidal-dl -l https://tidal/playlist/url
```
That's not exactly what you're expecting for, but maybe you could cron this command to automate stuff ?

Need time to investigate 😉

**Comment by cstaelen** [comment]
In first place, i can work on allow download of playlist by url in the app, it would be a first step !

**Comment by michaellunzer** [comment]
> In first place, i can work on allow download of playlist by url in the app, it would be a first step !

I like that idea! Thanks for getting back to me on this

**Comment by cstaelen** [comment]
Hi @michaellunzer i just released the 0.0.6 version.
Could you please pull latest docker image and try to download a playlist using the url ?
Thx :)

**Comment by michaellunzer** [comment]
awesome job! thanks for putting this together! 

I noticed a few things that should reflect this change:
1. on the home screen, you should put a hint that someone can put a public playlist URL in the search bar:

<img width="726" alt="image" src="https://github.com/cstaelen/tidarr/assets/10967175/d5d153d1-e656-4890-ae9d-63290300f5b4">

2. I'm not sure if it's just my docker paths but it put the playlist in the playlist folder inside the Album folder ```~/downloads/albums/playlist``` which is fine but maybe it makes sense to add a new volume (Playlists) to the `docker-compose` file and throw all the playlists in there. 
<img width="738" alt="image" src="https://github.com/cstaelen/tidarr/assets/10967175/0bd606cc-1393-41b4-be85-44eb968759a6">


Keep up the great work!

**Comment by cstaelen** [comment]
Hi @michaellunzer 
Thx for your suggestions :) 

I just updated the latest docker image with those two points 👍 

We are now able to mount the playlist folder in tidarr compose volume :
```yaml
volumes:
    - ...
    - /any/folder/to/download/playlists:/home/app/standalone/download/playlists
```

You may want to check your `playlistFolderFormat` option in `config/tidal-dl.json`.
Default configuration suggest `"playlistFolderFormat": "{PlaylistName}",`.

If you download an existing playlist, it will merge tracks.

Let me know if all is fine !
